### ISSUE TITLE
In Max Payne 2 "17_Crackhouse" and "18_Gognittis_Lot", there were many misplaced objects

### ISSUE THREAD

**Issue by FrankNiagra** [m0nstr0/max_payne_ldb_importer#15]
i ripped all Max Payne 2 maps to maya using this plugin, but I noticed problems in 2 maps, some rooms and objects were placed outside the map and unarragned.

https://github.com/m0nstr0/max_payne_ldb_importer/assets/149965975/dbde1d55-381d-44d9-8147-cb9867cac3e6

![Screenshot](https://github.com/m0nstr0/max_payne_ldb_importer/assets/149965975/85fbcc41-c104-47aa-b1fc-4f0a50466979)

And thank you so much for all the work, I was literally going to use a 3d ripping tool like 3DripperDX to rip each room out of a level and assemble them, problem was that 3DripperDX's models were skewed, and there were no textures, and some objects had problems with textures and required a tool for fixing, also another tool "ninjaripper" had it's problems.

**Comment by m0nstr0** [comment]
@FrankNiagra thanks for your feedback, i appreciate it. I made quick fix in the master branch. I checked out levels from this issue. Seems the problem to be fixed. You need to download the master branch. Please let me know if the problem is still there

**Comment by m0nstr0** [comment]
https://github.com/m0nstr0/max_payne_ldb_importer/releases/tag/1.0.1
