### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by ReindeerFloatilla** [m0nstr0/max_payne_ldb_importer#17]
Hi there I just discovered this project. I have a question. Could this program be modified into a obj or dae converter? So it could be used with blender or 3dsmax. Also could the process be reversed so we could export as well? That would make mapping for Max Payne 1 especially 100x easier if we could import and export geometry freely.

**Comment by m0nstr0** [comment]
1. LDB file format contains a lot of information like collisions, lightmaps, materials etc. It possible to write LDB exporter, but it will take a lot of time and resources and honestly Max Payne game is kind of outdated to spend so much time to this thing.

2. I don't use 3D Max or Blender but the codebase is divided to two parts, first part is depends on a modeling software and second doesn't. If someone has knowledge about 3D Max API or Blender API  it's kind of easy to modify the first part of the plugin to the specific API.
