### ISSUE TITLE
RAS files

### ISSUE THREAD

**Issue by r4v3n6101** [m0nstr0/max_payne_ldb_importer#7]
Hi there! Thanks for your work, I appreciate it and want to use some code for a project. I already know that I can use ras-maker for extracting .ldb and .kf2 files from inside game archives. But I want to go further and write ras-extractor. Do you have any researches about .ras format?

**Comment by m0nstr0** [comment]
No, I don't have. I haven't faced the need to work with this file format.

**Comment by r4v3n6101** [comment]
Well, that was a try. Thanks to you for the answer!
